services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: golang-app
    restart: always
    volumes:
      - .:/app
      - ./configs/config.yaml:/etc/app/config.yaml:ro
    ports:
      - "443:443"
    networks:
      - monitor_net
    depends_on:
      - postgres-dev
      - redis
    command: air -c .air.toml
  postgres-dev:
    image: harbor.local/dockerhub/postgres:15
    container_name: postgres-dev
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Shanghai
      - PGTZ=Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - monitor_net
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
  redis:
    image: harbor.local/dockerhub/redis:alpine3.22
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - monitor_net
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
  prometheus:
    image: harbor.local/dockerhub/prom/prometheus:v3.9.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-otlp-receiver"
    networks:
      - monitor_net
  tempo:
    image: harbor.local/dockerhub/grafana/tempo:2.10.0
    container_name: tempo
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3200:3200"
    networks:
      - monitor_net
  loki:
    image: harbor.local/dockerhub/grafana/loki:3.6.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor_net
  promtail:
    image: harbor.local/dockerhub/grafana/promtail:3.6.4
    container_name: promtail
    volumes:
      - ./logs:/var/log
      - ./configs/promtail-config.yaml:/etc/promtail/config.yaml
      - ./data/promtail-positions:/tmp
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - monitor_net
  grafana:
    image: harbor.local/dockerhub/grafana/grafana:12.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - monitor_net
networks:
  monitor_net:
    driver: bridge
